name: Release
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - fitch-dev
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        targets:
          [
            "x86_64-apple-darwin",
            "aarch64-apple-darwin",
            "x86_64-unknown-linux-gnu",
            "aarch64-unknown-linux-gnu",
          ]
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PACKAGES_TOKEN }}
          lfs: true
          submodules: recursive
          persist-credentials: false

      - name: SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_MYSTIKO_RUST }}
            ${{ secrets.SSH_PRIVATE_KEY_MYSTIKO_CIRCUITS }}
            ${{ secrets.SSH_PRIVATE_KEY_MYSTIKO_PROTOS }}
            ${{ secrets.SSH_PRIVATE_KEY_MYSTIKO_PROTOCOL }}

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build
        run: cross build --target ${{ matrix.targets }} --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.targets }}-binary
          path: target/${{ matrix.targets }}/release/mystiko

      - name: Telegram Failure Notification
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          message: ❗ Release failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PACKAGES_TOKEN }}
          lfs: true
          submodules: recursive
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python Dependencies
        run: pip install -r publish/requirements.txt

      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.targets }}-binary
          path: target/${{ matrix.targets }}/release/mystiko

      - name: Publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          export GIT_REVISION=$(git rev-parse --short HEAD)
          python3 publish/publish_binary.py target/x86_64-apple-darwin/release/mystiko x86_64-apple-darwin $GIT_REVISION
          python3 publish/publish_binary.py target/aarch64-apple-darwin/release/mystiko aarch64-apple-darwin $GIT_REVISION
          python3 publish/publish_binary.py target/x86_64-unknown-linux-gnu/release/mystiko x86_64-unknown-linux-gnu $GIT_REVISION
          python3 publish/publish_binary.py target/aarch64-unknown-linux-gnu/release/mystiko aarch64-unknown-linux-gnu $GIT_REVISION
          python3 publish/publish_index.py $GIT_REVISION

      - name: Telegram Failure Notification
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          message: ❗ Release failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}